TestTecnico/Models/ToDo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TestTecnico.Models
{
    public class ToDo
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Nombre { get; set; }
        [Required]
        [Display(Name = "Descripción")]
        public string Descripcion { get; set; }
        [Display(Name = "Tarea Lista?")]
        public bool Estado { get; set; }
        public string TipoAdjunto { get; set; }
        public string UrlAdjunto { get; set; }        
    }
}

TestTecnico/Controllers/ToDoController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.FileProviders;
using TestTecnico.Data;
using TestTecnico.Models;

namespace TestTecnico.Controllers
{
    public class ToDoController : Controller
    {
        private readonly TestTecnicoDbContext _context;
        private readonly IFileProvider fileProvider;
        private readonly IHostingEnvironment hostingEnvironment;

        public ToDoController(TestTecnicoDbContext context, IFileProvider fileprovider, IHostingEnvironment env)
        {
            _context = context;
            fileProvider = fileprovider;
            hostingEnvironment = env;
        }

        public async Task<IActionResult> Index(string filtroId, string filtroDescripcion, int listaEstados)
        {
            ViewData["CurrentFilter"] = filtroDescripcion;

            List<SelectListItem> selectEstados = new List<SelectListItem>();
            selectEstados.Add(new SelectListItem() { Text = "Todas", Value = "0" });
            selectEstados.Add(new SelectListItem() { Text = "Pendientes", Value = "1" });
            selectEstados.Add(new SelectListItem() { Text = "Finalizadas", Value = "2" });

            ViewBag.listaEstados = selectEstados;
            var toDo = from t in _context.ToDo
                           select t;
            if (!String.IsNullOrEmpty(filtroId))
            {
                toDo = toDo.Where(t => t.Id == Convert.ToInt32(filtroId));
            }
            if (!String.IsNullOrEmpty(filtroDescripcion))
            {
                toDo = toDo.Where(t => t.Descripcion.Contains(filtroDescripcion));
            }
            if (listaEstados == 1)
            {
                toDo = toDo.Where(t => t.Estado == false);
            }
            else if(listaEstados == 2)
            {
                toDo = toDo.Where(t => t.Estado == true);
            }
            return View(await toDo.AsNoTracking().ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var toDo = await _context.ToDo
                .FirstOrDefaultAsync(m => m.Id == id);
            if (toDo == null)
            {
                return NotFound();
            }

            return View(toDo);
        }

        public IActionResult Create()
        {
            var model = new ToDo();
            return PartialView("_AgregarToDo", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Descripcion,Estado,TipoAdjunto,UrlAdjunto")] ToDo model, IList<IFormFile> files)
        {
            if (ModelState.IsValid)
            {
                _context.Add(model);
                await _context.SaveChangesAsync();

                var supportedTypesImg = new[] { ".jpg", ".jpeg", ".tiff", ".gif", ".png" };
                var supportedTypesDoc = new[] { ".txt", ".doc", ".docx", ".pdf", ".xls", ".xlsx" };
                
                foreach (IFormFile source in files)
                {
                    if (source != null || source.Length != 0)
                    {
                        FileInfo fi = new FileInfo(source.FileName);

                        if (supportedTypesImg.Contains(fi.Extension))
                        {
                            var newFilename = model.Id + "_" + String.Format("{0:d}",
                                              (DateTime.Now.Ticks / 10) % 100000000) + fi.Extension;
                            var webPath = hostingEnvironment.WebRootPath;
                            var path = Path.Combine("", webPath + @"\ImageFiles\" + newFilename);

                            var pathToSave = @"/imageFiles/" + newFilename;

                            using (var stream = new FileStream(path, FileMode.Create))
                            {
                                await source.CopyToAsync(stream);
                            }
                            model.TipoAdjunto = fi.Extension;
                            model.UrlAdjunto = pathToSave;

                            _context.Update(model);
                            await _context.SaveChangesAsync();
                        }
                        else if (supportedTypesDoc.Contains(fi.Extension))
                        {
                            var newFilename = model.Id + "_" + String.Format("{0:d}",
                                              (DateTime.Now.Ticks / 10) % 100000000) + fi.Extension;
                            var webPath = hostingEnvironment.WebRootPath;
                            var path = Path.Combine("", webPath + @"\docFiles\" + newFilename);

                            var pathToSave = @"/docFiles/" + newFilename;

                            using (var stream = new FileStream(path, FileMode.Create))
                            {
                                await source.CopyToAsync(stream);
                            }
                            model.TipoAdjunto = fi.Extension;
                            model.UrlAdjunto = pathToSave;
                            _context.Update(model);
                            await _context.SaveChangesAsync();
                        }

                    }
                }                

                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction("Create");
        }

        public async Task<IActionResult> Edit(int? id)
        {
            var supportedTypesImg = new[] { ".jpg", ".jpeg", ".tiff", ".gif", ".png" };
            var supportedTypesDoc = new[] { ".txt", ".doc", ".docx", ".pdf", ".xls", ".xlsx" };

            ViewBag.supportedTypesImg = supportedTypesImg;
            ViewBag.supportedTypesDoc = supportedTypesDoc;
            if (id == null)
            {
                return NotFound();
            }
            var toDo = await _context.ToDo.FindAsync(id);

            if (toDo == null)
            {
                return NotFound();
            }

            return PartialView("_ModificarToDo", toDo);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ToDo model, IList<IFormFile> files)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var supportedTypesImg = new[] { ".jpg", ".jpeg", ".tiff", ".gif", ".png" };
                    var supportedTypesDoc = new[] { ".txt", ".doc", ".docx", ".pdf", ".xls", ".xlsx" };

                    foreach (IFormFile source in files)
                    {
                        if (source != null || source.Length != 0)
                        {
                            FileInfo fi = new FileInfo(source.FileName);

                            if (supportedTypesImg.Contains(fi.Extension))
                            {
                                var newFilename = model.Id + "_" + String.Format("{0:d}",
                                                  (DateTime.Now.Ticks / 10) % 100000000) + fi.Extension;
                                var webPath = hostingEnvironment.WebRootPath;
                                var path = Path.Combine("", webPath + @"\ImageFiles\" + newFilename);

                                var pathToSave = @"/imageFiles/" + newFilename;

                                using (var stream = new FileStream(path, FileMode.Create))
                                {
                                    await source.CopyToAsync(stream);
                                }
                                model.TipoAdjunto = fi.Extension;
                                model.UrlAdjunto = pathToSave;

                                _context.Update(model);
                                await _context.SaveChangesAsync();
                            }
                            else if (supportedTypesImg.Contains(fi.Extension))
                            {
                                var newFilename = model.Id + "_" + String.Format("{0:d}",
                                                  (DateTime.Now.Ticks / 10) % 100000000) + fi.Extension;
                                var webPath = hostingEnvironment.WebRootPath;
                                var path = Path.Combine("", webPath + @"\docFiles\" + newFilename);

                                var pathToSave = @"/docFiles/" + newFilename;

                                using (var stream = new FileStream(path, FileMode.Create))
                                {
                                    await source.CopyToAsync(stream);
                                }
                                model.TipoAdjunto = fi.Extension;
                                model.UrlAdjunto = pathToSave;
                                _context.Update(model);
                                await _context.SaveChangesAsync();
                            }

                        }
                    }
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ToDoExists(model.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

TestTecnico/Views/ToDo/Index.cshtml
@model IEnumerable<TestTecnico.Models.ToDo>

@{
    ViewData["Title"] = "Tareas";
}
@{
    Layout = null;
}

<script src="~/lib/jquery/dist/jquery.js"></script>

<script src="~/js/index.js"></script>
<link href="~/css/index.css" rel="stylesheet" />
<script src="~/js/site.js"></script>

<div id="modal-placeholder"></div>
<div id="editModal"></div>


<p>
    <button type="button" class="btn btn-primary" data-toggle="ajax-modal" data-target="#add-contact" data-url="@Url.Action("Create")">
        Agregar Tareas
    </button>
</p>
<link href="//netdna.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
<body>
    <div class="container-fluid">
        <form asp-action="Index" method="get">
            <div class="form-actions no-color">
                <p>
                    Filtrar Por Id: <input type="text" name="filtroId" id="numeric" value="@ViewData["filtroId"]" />

                    Filtrar Por Descripción: <input type="text" name="filtroDescripcion" value="@ViewData["currentFilter"]" />

                    Filtrar Por Estado:
                    @Html.DropDownList("listaEstados")
                    <input type="submit" value="Buscar" class="btn btn-default" />

                </p>
                
            </div>
            <div class="form-actions no-color">
                
            </div>
            <div class="form-actions no-color">
                
            </div>
        </form>
        <div id="sortableKanbanBoards" class="row">
            <div class="panel panel-primary kanban-col" style="float: none; margin: 0 auto;">
                <div class="panel-heading">
                    <div class="alert alert-danger">TODO</div>
                    
                    <i class="fa fa-2x fa-plus-circle pull-right"></i>
                </div>
                <div class="panel-body">
                    <div id="TODO" class="kanban-centered">
                        @foreach (var item in Model)
                        {
                            @if (!item.Estado)
                            {

                                <article class="kanban-entry" id="item+@item.Id">
                                    <div class="kanban-entry-inner">
                                        <div class="kanban-label">
                                            <h2>
                                                <button id="editToDo" data-toggle="ajax-modal" data-target="#edit-Modal" class="btn btn-primary" data-id="@item.Id" data-url="@Url.Action("Edit", new { id = item.Id})">@item.Nombre</button>
                                                  Id : @item.Id
                                            </h2>
                                            <p>@item.Descripcion</p>
                                            <div>
                                                <form asp-action="Delete" asp-route-id="@item.Id" data-ajax="true" onclick="return confirm('Seguro deseas borrar la tarea?')">
                                                    <button type="submit" class="btn btn-sm btn-danger d-md-inline-block">
                                                        Borrar
                                                    </button>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </article>
                            }

                        }
                    </div>
                </div>

            </div>
            <div class="panel panel-primary kanban-col" style="float: none; margin: 0 auto;">
                <div class="panel-heading">
                    <div class="alert alert-success">DONE</div>                    
                    <i class="fa fa-2x fa-plus-circle pull-right"></i>
                </div>
                <div class="panel-body">
                    <div id="DONE" class="kanban-centered">
                        @foreach (var item in Model)
                        {
                            @if (item.Estado)
                            {
                                <article class="kanban-entry" id="item+@item.Id">
                                    <div class="kanban-entry-inner">
                                        <div class="kanban-label">
                                            <h2>
                                                <button id="editToDo" data-toggle="ajax-modal" data-target="#edit-Modal" class="btn btn-primary" data-id="@item.Id" data-url="@Url.Action("Edit", new { id = item.Id})">@item.Nombre</button>
                                                Id : @item.Id
                                            </h2>
                                            <p>@item.Descripcion</p>
                                            <div>
                                                <form asp-action="Delete" asp-route-id="@item.Id" data-ajax="true" onclick="return confirm('Seguro deseas borrar la tarea?')">
                                                    <button type="submit" class="btn btn-sm btn-danger d-md-inline-block">
                                                        Borrar
                                                    </button>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </article>
                            }

                        }
                    </div>
                </div>

            </div>
        </div>
    </div>
</body>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TestTecnico/Views/ToDo/_AgregarToDo.cshtml
@model TestTecnico.Models.ToDo

<hr />
<div class="modal fade" id="add-contact" tabindex="-1" role="dialog" aria-labelledby="addContactLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addContactLabel">Agregar Tarea</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <form asp-controller="ToDo" asp-action="Create" method="post" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="modal-body">
                    <div name="IsValid" type="hidden" value="@ViewData.ModelState.IsValid.ToString()" />
                    <div class="form-group">
                        <label asp-for="Nombre"></label>
                        <input asp-for="Nombre" class="form-control" />
                        <span asp-validation-for="Nombre" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Descripcion"></label>
                        <input asp-for="Descripcion" class="form-control" rows="10"/>
                        <span asp-validation-for="Descripcion" class="text-danger"></span>
                    </div>
                    <div class="form-group form-check">
                        <label class="form-check-label">
                            <input class="form-check-input" asp-for="Estado" /> @Html.DisplayNameFor(model => model.Estado)
                        </label>
                    </div>
                    <div class="form-group">
                        <div class="col-md-10">
                            <p>Cargar Archivo</p>
                            <input type="file" name="files" onchange="ShowPreview(this)" />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-10">
                            <img id="impPrev" height="200" style="display:none" />
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                    <input type="submit" class="btn btn-primary" id="submit" value="Aceptar" />
                </div>
            </form>

        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}

TestTecnico/Views/ToDo/_ModificarToDo.cshtml
@model TestTecnico.Models.ToDo

<hr />
<div class="modal fade" id="edit-Modal" tabindex="-1" role="dialog" aria-labelledby="addContactLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editContactLabel">Modificar Tarea</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" id="closeModal">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <form asp-controller="ToDo" asp-action="Edit" method="post" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="modal-body">
                    <input name="IsValid" type="hidden" value="@ViewData.ModelState.IsValid.ToString()" />

                    <input type="hidden" asp-for="Id" />
                    <div class="form-group">
                        <label asp-for="Nombre" class="control-label"></label>
                        <input asp-for="Nombre" class="form-control" />
                        <span asp-validation-for="Nombre" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Descripcion" class="control-label"></label>
                        <input asp-for="Descripcion" class="form-control" rows="10" />
                        <span asp-validation-for="Descripcion" class="text-danger"></span>
                    </div>
                    <div class="form-group form-check">
                        <label class="form-check-label">
                            <input class="form-check-input" asp-for="Estado" /> @Html.DisplayNameFor(model => model.Estado)
                        </label>
                    </div>
                    @if (Model.UrlAdjunto != null)
                    {
                        if (Model.TipoAdjunto.Contains("jpg"))
                        {
                            <div class="form-group">
                                <div class="col-md-10">
                                    <input type="image" asp-for="UrlAdjunto" src="@Model.UrlAdjunto" name="files" height="200" />
                                </div>
                            </div>
                        }
                        else
                        {
                            <div class="form-group">
                                <div class="col-md-10">
                                    <input type="file" asp-for="UrlAdjunto" src="@Model.UrlAdjunto" name="files" height="200" />
                                </div>
                            </div>
                        }

                    }
                    else
                    {
                        <div class="form-group">
                            <div class="col-md-10">
                                <p>Cargar Archivo</p>
                                <input type="file" name="files" asp-for="UrlAdjunto" onchange="ShowPreview(this)" />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-10">
                                <input type="image" name="files" id="impPrev" height="200" style="display:none" asp-for="UrlAdjunto" />
                            </div>
                        </div>
                    }
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                        <input type="submit" class="btn btn-primary" id="submit" value="Actualizar" />
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}